/* DO NOT EDIT THIS FILE - it is machine generated */
#include "includes.h"
/* Header for class dev_westy_Injector */

#ifndef _Included_dev_westy_Injector
#define _Included_dev_westy_Injector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_westy_Injector
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_westy_Injector_getVersion
  (JNIEnv *, jclass);
JNIEXPORT jint JNICALL Java_dev_westy_Injector_injectDll(JNIEnv*, jclass, jint pid, jbyteArray bytes, jint bytesLenght);

#ifdef __cplusplus
}
#endif
#endif
